_target_: envs.WorldModelEnvConfig
horizon: 15
num_batches_to_preload: 256
diffusion_sampler:
  _target_: models.diffusion.DiffusionSamplerConfig
  num_steps_denoising: 3
  sigma_min: 2e-3
  sigma_max: 5.0
  rho: 7
  order: 1  # 1: Euler, 2: Heun
  s_churn: 0.0  # Amount of stochasticity
  s_tmin: 0.0
  s_tmax: ${eval:'float("inf")'}
  s_noise: 1.0
